site_name: GreenWeb.js

nav:
    - 'Modules':
        - 'xch':
            - 'Module Overview': 'xch/index.md'
            - 'Provider': 'xch/provider.md'
            - 'LeafletProvider': 'xch/leaflet-provider.md'
            - 'GobyProvider': 'xch/goby-provider.md'
            - 'MultiProvider': 'xch/multi-provider.md'
        - 'clvm':
            - 'Module Overview': 'clvm/index.md'
        - 'util':
            - 'Module Overview': 'util/index.md'
            - 'address': 'util/address.md'
            - 'coin': 'util/coin.md'
            - 'serializer': 'util/serializer.md'
    - License: 'license.md'

markdown_extensions:
    - def_list
    - tables
    - toc:
        permalink: "#"
