site_name: GreenWeb.js

nav:
    - 'Modules':
        - 'blockchain': 'blockchain/index.md'
            - 'Module Overview': 'blockchain/index.md'
            - 'Examples': 'blockchain/examples.md'
        - 'wallet': 'wallet/index.md'
            - 'Module Overview': 'wallet/index.md'
            - 'Examples': 'waller/examples.md'
        - 'clvm': 'clvm/index.md'
            - 'Module Overview': 'clvm/index.md'
            - 'Examples': 'clvm/examples.md'
        - 'util': 'util/index.md'
            - 'Module Overview': 'util/index.md'
            - 'Examples': 'util/examples.md'
    - License: 'license.md'

markdown_extensions:
    - def_list
    - tables
    - toc:
        permalink: "#"
