site_name: GreenWeb.js

nav:
    - 'Modules':
        - 'blockchain':
            - 'Module Overview': 'blockchain/index.md'
            - 'BlockchainProvider': 'blockchain/blockchain-provider.md'
            - 'LeafletProvider': 'blockchain/leaflet-provider.md'
        - 'wallet':
            - 'Module Overview': 'wallet/index.md'
        - 'clvm':
            - 'Module Overview': 'clvm/index.md'
        - 'util':
            - 'Module Overview': 'util/index.md'
            - 'address': 'util/address.md'
            - 'coin': 'util/coin.md'
            - 'serializer': 'util/serializer.md'
    - License: 'license.md'

markdown_extensions:
    - def_list
    - tables
    - toc:
        permalink: "#"
